# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jackieqin/Documents/CLionProjects/final-project-xwang287-xliu326-bqin004

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jackieqin/Documents/CLionProjects/final-project-xwang287-xliu326-bqin004

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.19.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jackieqin/Documents/CLionProjects/final-project-xwang287-xliu326-bqin004/CMakeFiles /Users/jackieqin/Documents/CLionProjects/final-project-xwang287-xliu326-bqin004//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jackieqin/Documents/CLionProjects/final-project-xwang287-xliu326-bqin004/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

#=============================================================================
# Target rules for targets named libMonopoly

# Build rule for target.
libMonopoly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libMonopoly
.PHONY : libMonopoly

# fast build rule for target.
libMonopoly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/build
.PHONY : libMonopoly/fast

#=============================================================================
# Target rules for targets named unit_test

# Build rule for target.
unit_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_test
.PHONY : unit_test

# fast build rule for target.
unit_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/build
.PHONY : unit_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/Card.o: src/Card.cpp.o

.PHONY : src/Card.o

# target to build an object file
src/Card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/Card.cpp.o
.PHONY : src/Card.cpp.o

src/Card.i: src/Card.cpp.i

.PHONY : src/Card.i

# target to preprocess a source file
src/Card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/Card.cpp.i
.PHONY : src/Card.cpp.i

src/Card.s: src/Card.cpp.s

.PHONY : src/Card.s

# target to generate assembly for a file
src/Card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/Card.cpp.s
.PHONY : src/Card.cpp.s

src/dice.o: src/dice.cpp.o

.PHONY : src/dice.o

# target to build an object file
src/dice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/dice.cpp.o
.PHONY : src/dice.cpp.o

src/dice.i: src/dice.cpp.i

.PHONY : src/dice.i

# target to preprocess a source file
src/dice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/dice.cpp.i
.PHONY : src/dice.cpp.i

src/dice.s: src/dice.cpp.s

.PHONY : src/dice.s

# target to generate assembly for a file
src/dice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/dice.cpp.s
.PHONY : src/dice.cpp.s

src/gameManager.o: src/gameManager.cpp.o

.PHONY : src/gameManager.o

# target to build an object file
src/gameManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/gameManager.cpp.o
.PHONY : src/gameManager.cpp.o

src/gameManager.i: src/gameManager.cpp.i

.PHONY : src/gameManager.i

# target to preprocess a source file
src/gameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/gameManager.cpp.i
.PHONY : src/gameManager.cpp.i

src/gameManager.s: src/gameManager.cpp.s

.PHONY : src/gameManager.s

# target to generate assembly for a file
src/gameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/gameManager.cpp.s
.PHONY : src/gameManager.cpp.s

src/location.o: src/location.cpp.o

.PHONY : src/location.o

# target to build an object file
src/location.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/location.cpp.o
.PHONY : src/location.cpp.o

src/location.i: src/location.cpp.i

.PHONY : src/location.i

# target to preprocess a source file
src/location.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/location.cpp.i
.PHONY : src/location.cpp.i

src/location.s: src/location.cpp.s

.PHONY : src/location.s

# target to generate assembly for a file
src/location.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/location.cpp.s
.PHONY : src/location.cpp.s

src/locationEvent.o: src/locationEvent.cpp.o

.PHONY : src/locationEvent.o

# target to build an object file
src/locationEvent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/locationEvent.cpp.o
.PHONY : src/locationEvent.cpp.o

src/locationEvent.i: src/locationEvent.cpp.i

.PHONY : src/locationEvent.i

# target to preprocess a source file
src/locationEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/locationEvent.cpp.i
.PHONY : src/locationEvent.cpp.i

src/locationEvent.s: src/locationEvent.cpp.s

.PHONY : src/locationEvent.s

# target to generate assembly for a file
src/locationEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/locationEvent.cpp.s
.PHONY : src/locationEvent.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/phase.o: src/phase.cpp.o

.PHONY : src/phase.o

# target to build an object file
src/phase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/phase.cpp.o
.PHONY : src/phase.cpp.o

src/phase.i: src/phase.cpp.i

.PHONY : src/phase.i

# target to preprocess a source file
src/phase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/phase.cpp.i
.PHONY : src/phase.cpp.i

src/phase.s: src/phase.cpp.s

.PHONY : src/phase.s

# target to generate assembly for a file
src/phase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/phase.cpp.s
.PHONY : src/phase.cpp.s

src/role.o: src/role.cpp.o

.PHONY : src/role.o

# target to build an object file
src/role.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/role.cpp.o
.PHONY : src/role.cpp.o

src/role.i: src/role.cpp.i

.PHONY : src/role.i

# target to preprocess a source file
src/role.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/role.cpp.i
.PHONY : src/role.cpp.i

src/role.s: src/role.cpp.s

.PHONY : src/role.s

# target to generate assembly for a file
src/role.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libMonopoly.dir/build.make CMakeFiles/libMonopoly.dir/src/role.cpp.s
.PHONY : src/role.cpp.s

test/unit_test.o: test/unit_test.cpp.o

.PHONY : test/unit_test.o

# target to build an object file
test/unit_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/unit_test.cpp.o
.PHONY : test/unit_test.cpp.o

test/unit_test.i: test/unit_test.cpp.i

.PHONY : test/unit_test.i

# target to preprocess a source file
test/unit_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/unit_test.cpp.i
.PHONY : test/unit_test.cpp.i

test/unit_test.s: test/unit_test.cpp.s

.PHONY : test/unit_test.s

# target to generate assembly for a file
test/unit_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit_test.dir/build.make CMakeFiles/unit_test.dir/test/unit_test.cpp.s
.PHONY : test/unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Game"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... libMonopoly"
	@echo "... unit_test"
	@echo "... src/Card.o"
	@echo "... src/Card.i"
	@echo "... src/Card.s"
	@echo "... src/dice.o"
	@echo "... src/dice.i"
	@echo "... src/dice.s"
	@echo "... src/gameManager.o"
	@echo "... src/gameManager.i"
	@echo "... src/gameManager.s"
	@echo "... src/location.o"
	@echo "... src/location.i"
	@echo "... src/location.s"
	@echo "... src/locationEvent.o"
	@echo "... src/locationEvent.i"
	@echo "... src/locationEvent.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/phase.o"
	@echo "... src/phase.i"
	@echo "... src/phase.s"
	@echo "... src/role.o"
	@echo "... src/role.i"
	@echo "... src/role.s"
	@echo "... test/unit_test.o"
	@echo "... test/unit_test.i"
	@echo "... test/unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

